#!/bin/bash
export LC_NUMERIC=C

# Close STDERR FD
#exec 2<&-
# Open STDOUT as $LOG_FILE file for read and write.
#exec 2<>/tmp/index.log

function extractFilename {
	local filename=$(basename -- "${1}")
	echo ${filename%.*}
}

#https://stackoverflow.com/questions/38972736/how-to-print-lines-between-two-patterns-inclusive-or-exclusive-in-sed-awk-or

gpxMainFile=$1
gpxDir=$(extractFilename ${gpxMainFile})
gpxHead=$(mktemp)

echo "gpxMainFile=$gpxMainFile"
echo "gpxDir=$gpxDir"
#cat -n ${gpxMainFile}
#cat -n ${gpxMainFile} | grep "<trk>"
echo "##############"
awk "/<\?xml/{flag=1} /<trk>/{flag=0} flag" ${gpxMainFile}

#while IFS= read -r line; do
#	echo "Line ${line}" >&2
#done < <(grep -Fn "trk>" ${gpxMainFile} | cut -d ":" -f1)

trk_array=( $(grep -Fn "trk>" ${gpxMainFile} | cut -d ":" -f1) )

for i in `seq 0 2 $((${#trk_array[@]}-1))`; do
	ii=$(printf "Decimal: %02d")
     echo "$ii. Interval TRK ${trk_array[$i]}-${trk_array[$((i+1))]}"
done


rm -f ${gpxHead}


