#!/bin/bash
export LC_NUMERIC=C

# Close STDERR FD
#exec 2<&-
# Open STDOUT as $LOG_FILE file for read and write.
#exec 2<>/tmp/index.log


osmurl="https://www.openstreetmap.org/api/0.6"

#echo "Our temp file is ${TMPDIR}" >&2
parted=false;

function distance () {
	local lat1=$(bc -l <<< "${1%,*} * 0.01745329251994329444")
	local lat2=$(bc -l <<< "${2%,*} * 0.01745329251994329444")
        local dlon=`bc -l <<< "(${2##*,} - ${1##*,}) * 0.01745329251994329444"`
	local distance=$(bc -l <<< "s($lat1) * s($lat2) + c($lat1) * c($lat2) * c($dlon)")
	distance=$(bc -l <<<"1.5707963267948965 - a($distance / sqrt(1 - $distance * $distance))")
	distance=$(bc -l <<<"scale=4; ($distance * 6371 + 0.00005) / 1")
	echo $distance | awk '{printf "%1.4f\n", $1}'
}

function addFloat {
	num=$(bc -l <<<"scale=4; ($1 + $2)")
	echo $num | awk '{printf "%1.4f\n", $1}'
}

function checkFileTime {
	local file=$1
	local maxTime=${2:-3600}
	local diffTime=0;
	if [ -e "${file}" ]; then
		local fileTime=$(stat --format='%Y' "${file}")
		local currTime=$(date +%s)
		diffTime=$(($currTime-$fileTime));
	        echo "The $file is "$(bc -l <<<"scale=1;$diffTime/3600")" hour(s) old." >&2
	        diffTime=$((${diffTime}-${maxTime}));
		if [ ${diffTime} -ge 0 ]; then
		        return 1;
		fi;
	else
	        echo "The $file not found!" >&2
	        return 1;
	fi;
}

function downloadOsmPart {
	local filename="${TMPDIR}/${1}.xml"
	filename=${filename/\/full/-full}
	[ -d ${filename%/*} ] || mkdir -p ${filename%/*}
	checkFileTime "${filename}"
	if [ $? -ne 0 ]; then
		http=$(curl --silent --head "${osmurl}/${1}" | grep "HTTP\/[1-2].* [2\d\d]")
		if [ $? -ne 0 ]; then
        		echo -e "ERROR ${osmurl}/${1}\n url not found!" >&2
        		if [ -e ${filename} ]; then
       				echo "Use cache older file ${filename}" >&2
       				return 0;
       			fi;
        		return 1;
        	fi
        	echo "Download ... ${osmurl}/${1}" >&2
        	curl --silent "${osmurl}/${1}" -o ${filename}
        	local status=$?
        else
		echo "Use cache file ${filename}" >&2
	fi;
#	ls -la ${filename} >&2
	ls ${filename}
}

TMPDIR="./tmp"

while [ $# -ne 0 ]; do
	arg="$1"
	case "${arg}" in
		--output|-o)
			shift;
			gpxfile=$1
			;;
		--outputv|-ov)
			shift;
			gpxfile=$1
			validate=true
			;;
		--reverse|-r)
			reverse=true
			;;
		--parted|-p)
			parted=true
			;;
		--dir|-d)
			TMPDIR=$1
			;;
		rel*|r*)
			objectid=${1/"rel"/"r"}
			objectid=${objectid:1}
			type="rel"
			;;
		way*|w*)
			objectid=${1/"way"/"w"}
			objectid=${objectid:1}
			type="way"
			;;
		*)
			objectid=${1}
			type="rel"
			;;
	esac
	shift
done

if [ -z ${TMPDIR} ]; then
	TMPDIR=$(mktemp -d) || exit 1
	trap 'rm -rf "${TMPDIR}"' EXIT
fi;

gpx_start=$(cat <<EOM1
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<gpx version="1.1"
	creator="way2gpx - https://osm.slavics.cz"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.topografix.com/GPX/1/1"
	xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
EOM1
)

if [ -z "${objectid}" ]; then
	echo -e "$0 [--reverse|-r] [--validation|-v] [--parted|-p] [--output|-o file.gpx] [rel|r][way|w]numberofobject" >&2
	echo -e "\tconvert osm relation to gpx" >&2
#	echo -e "\t--reverse|-r\t: reverse path (only way), default: false" >&2
	echo -e "\t--parted|-p\t: division path (only relation), default: false" >&2
#	echo -e "\t--output|-o gpxfile\t: export to file" >&2
	echo -e "\t--validate|-v\t: export with GPX validation, default: false" >&2
	echo -e "\trel|r\t: numberofobject is relation (default)" >&2
	echo -e "\tway|w\t: numberofobject is way" >&2
	echo -e "\nExample\t$0 -r 327119963" >&2
	echo -e "\t$0 rel6452264" >&2
	exit 1;
fi

function checkGarminColour {
	local colour=${1,,}
	colour=${colour^}
	local arraycolor=(Black DarkRed DarkGreen DarkYellow DarkBlue DarkMagenta DarkCyan LightGray DarkGray Red Green Yellow Blue Magenta Cyan White Transparent)
	if [[ " ${arraycolor[@]} " =~ " ${colour} " ]]; then
		echo -e $colour
		return 0;
	else
		return 1;
	fi;
}

function getBoundary {
	local file=$1

	# Boundary
	cut -d ' ' -f2 "${file}" | sort -t ',' -k1 | head -n 1 | cut -d ',' -f1
	cut -d ' ' -f2 "${file}" | sort -r -t ',' -k1 | head -n 1 | cut -d ',' -f1
	cut -d ' ' -f2 "${file}" | sort -t ',' -k2 | head -n 1 | cut -d ',' -f2
	cut -d ' ' -f2 "${file}" | sort -r -t ',' -k2 | head -n 1 | cut -d ',' -f2

	# Last Timestamp
	sort "${file}" -r -k 3 | head -n 1 | cut -d ' ' -f 3
}

function generateWay {
	local wayid=$1
	local isReverse=$2
	echo -en "\n" >&2
	local osmfile=$(downloadOsmPart way/${wayid}/full)
	[ "$osmfile" == "" ] && exit 1

	echo "Extract data from '${osmfile}' $isReverse" >&2
	isReverse=${isReverse/"backward"/"true"}
	
	local NODEFILE=$(mktemp) || exit 1

	local name=$(grep -oP '<tag(.*) k=\"name\"(.*) v="\K[^"]*' ${osmfile} | tr -d '\n')
	local desc=$(grep -oP '<tag(.*) k=\"description\"(.*) v="\K[^"]*' ${osmfile} | tr -d '\n')
	local note=$(grep -oP '<tag(.*) k=\"note\"(.*) v="\K[^"]*' ${osmfile} | tr -d '\n')
	local type1=$(grep -oP '<tag(.*) k=\"highway\"(.*) v="\K[^"]*' ${osmfile} | tr -d '\n')
	local website=$(grep -oP '<tag(.*) k=\"website\"(.*) v="\K[^"]*' ${osmfile} | tr -d '\n')
	local colour=$(grep -oP '<tag(.*) k=\"colour\"(.*) v="\K[^"]*' ${osmfile} | tr -d '\n')
	local author=$(grep -oP '<way(.*) user="\K[^"]*' ${osmfile} | tr -d '\n')
	local wayts=$(grep -oP '<way(.*) timestamp="\K[^"]*' ${osmfile} | tr -d '\n')

	#[ "$name" == "" ] && name=${wayid}

	echo "Extract coordinates from $wayid" >&2

	grep "<node" ${osmfile} | while read -r line; do
	#	echo "$line"
		visible=$(echo ${line} | grep -oP '<node(.*) visible="\K[^"]*' | tr -d '\n')
		[ "${visible}" != "true" ] && continue
		id=$(echo ${line} | grep -oP '<node(.*) id="\K[^"]*' | tr -d '\n')
		ts=$(echo ${line} | grep -oP '<node(.*) timestamp="\K[^"]*' | tr -d '\n')
		lat=$(echo ${line} | grep -oP '<node(.*) lat="\K[^"]*' | tr -d '\n')
		lon=$(echo ${line} | grep -oP '<node(.*) lon="\K[^"]*' | tr -d '\n')
		echo "$id $lat,$lon $ts" >> ${NODEFILE}
	done

	declare -A coordinates
	while read -r line; do
		id=$(echo $line | cut -d ' ' -f1)
		ll=$(echo $line | cut -d ' ' -f2)
		coordinates["${id}"]="$ll"
	done < ${NODEFILE}

	echo "Check boundary" >&2
	local latmin latmax lonmin lonmax lastts
	read -r -d '' latmin latmax lonmin lonmax lastts <<< $(getBoundary ${NODEFILE} )
	#echo $latmin $latmax $lonmin $lonmax $lastts >&2

	lastts=$(echo -e "${lastts}\n${wayts}" | sort -r | head -n 1)

	rm -vf ${NODEFILE} >&2

	declare -a nodes
	local nodes=( `grep -oP '<nd(.*) ref="\K[^"]*' ${osmfile}` )

	if [ "$isReverse" == "true" ]; then
		echo "Reverse nodes..." >&2
		min=0
		max=$(( ${#nodes[@]} -1 ))
		while [[ $min -lt $max ]]; do
			# Swap current first and last elements
			x="${nodes[$min]}"
			nodes[$min]="${nodes[$max]}"
			nodes[$max]="$x"
			# Move closer
			(( min++, max-- ))
		done
	fi;

	echo "Last timestamp="${lastts} >&2

#	echo "Name=$name" >&2
#	echo "Author=$author" >&2
#	[ "$desc" != "" ] && echo "Description: $desc"
#	[ "$note" != "" ] && echo "Note: $note"
	
	local year=$(date +%Y)
	local gpx_metadata="\t<metadata>\n\t</metadata>"
	[ "${name}" != "" ] && gpx_metadata=${gpx_metadata/"\t</metadata>"/"\t\t<name>${name}</name>\n\t</metadata>"}
	[ "${desc}${note}" != "" ] && gpx_metadata=${gpx_metadata/"\t</metadata>"/"\t\t<desc>${desc}${note}</desc>\n\t</metadata>"}
	[ "${author}" != "" ] && gpx_metadata=${gpx_metadata/"\t</metadata>"/"\t\t<author>\n\t\t\t<name>${author}</name>\n\t\t</author>\n\t</metadata>"}
	gpx_metadata=${gpx_metadata/"\t</metadata>"/"\t\t<copyright author=\"© OpenStreetMap contributors\">\n\t\t\t<year>${year}</year>\n\t\t\t<license>https://opendatacommons.org/licenses/odbl/</license>\n\t\t</copyright>\n\t</metadata>"}
	echo "src='${website}'"
	[ "${website}" != "" ] && gpx_metadata=${gpx_metadata/"\t</metadata>"/"\t\t<link href=\"${website}\"/>\n\t</metadata>"}
	[ "${lastts}" != "" ] && gpx_metadata=${gpx_metadata/"\t</metadata>"/"\t\t<time>${lastts}</time>\n\t</metadata>"}
	gpx_metadata=${gpx_metadata/"\t</metadata>"/"\t\t<bounds minlat=\"${latmin}\" maxlat=\"${latmax}\" minlon=\"${lonmin}\" maxlon=\"${lonmax}\"/>\n\t</metadata>"}

	gpx_trkhead="<trk>"
	[ "$name" != "" ] && gpx_trkhead="${gpx_trkhead}\n\t\t<name>$name</name>"
	gpx_trkhead="${gpx_trkhead}\n\t\t<src>OpenStreetMap</src>"
	gpx_trkhead="${gpx_trkhead}\n\t\t<link href=\"https://www.openstreetmap.org/way/${wayid}\"><text>${wayid}</text></link>"
	gpx_trkhead="${gpx_trkhead}\n\t\t<type>${type1}</type>"
		
	colour=$(checkGarminColour ${colour})
	if [ $? -eq 0 ]; then
		echo "Set color: ${colour}" >&2
		gpx_trkhead="${gpx_trkhead}\n\t\t<extensions>\n\t\t\t<gpxx:TrackExtension xmlns:gpxx=\"http://www.garmin.com/xmlschemas/GpxExtensions/v3\">\n\t\t\t\t<gpxx:DisplayColor>${colour}</gpxx:DisplayColor>\n\t\t\t</gpxx:TrackExtension>\n\t\t</extensions>"
	fi;

	echo -e "${gpx_start}" 
	echo -e "${gpx_metadata}"
	echo -e "\t${gpx_trkhead}"
	echo -e "\t\t<trkseg>"

	for ((i = 0; i < ${#nodes[@]}; i++)); do
		n=${nodes[$i]};
		coordinate=${coordinates[$n]};
		echo -e "\t\t\t<trkpt lat=\"${coordinate%,*}\" lon=\"${coordinate##*,}\"/>"
		
#		if [ $i -ne 0 ]; then
#			dist=$(distance $lastcoo ${coordinates[$n]})
#			sumdist=$(echo "${sumdist:-0} + $dist" | bc -l)
			#echo " $dist $sumdist"
#		fi;
#		lastcoo=${coordinate}
	done
	echo -e "\t\t</trkseg>"
	echo -e "\t</trk>"
	echo -e "</gpx>"
	echo $sumdist | awk '{printf "Distance %1.4f km\n", $1}' >&2
}

function generateRelation {
	local relid=$1
	local osmfile=$(downloadOsmPart relation/${relid})
	echo "osmfile=$osmfile"
	[ "$osmfile" == "" ] && exit 1
	local patternTrkSeg="/<trkseg>/{flag=1; next} /<\/trkseg>/{flag=0} flag"
	local patternTrk="/<trk>/{flag=1; next} /<\/trk>/{flag=0} flag"
	
	local name=$(grep -oP '<tag(.*) k=\"name\"(.*) v="\K[^"]*' ${osmfile} | tr -d '\n')
	local desc=$(grep -oP '<tag(.*) k=\"description\"(.*) v="\K[^"]*' ${osmfile} | tr -d '\n')
	local note=$(grep -oP '<tag(.*) k=\"note\"(.*) v="\K[^"]*' ${osmfile} | tr -d '\n')
	local website=$(grep -oP '<tag(.*) k=\"website\"(.*) v="\K[^"]*' ${osmfile} | tr -d '\n')
	local colour=$(grep -oP '<tag(.*) k=\"colour\"(.*) v="\K[^"]*' ${osmfile} | tr -d '\n')
	local distance=$(grep -oP '<tag(.*) k=\"distance\"(.*) v="\K[^"]*' ${osmfile} | tr -d '\n')
	local author=$(grep -oP '<rel(.*) user="\K[^"]*' ${osmfile} | tr -d '\n')
	local relts=$(grep -oP '<rel(.*) timestamp="\K[^"]*' ${osmfile} | tr -d '\n')
	local operator=$(grep -oP '<tag(.*) k=\"operator\"(.*) v="\K[^"]*' ${osmfile} | tr -d '\n')
	local network=$(grep -oP '<tag(.*) k=\"network\"(.*) v="\K[^"]*' ${osmfile} | tr -d '\n')

	echo "Extract ways from ${osmfile}" >&2
	local WAYSFILE=$(mktemp) || exit 1
	grep '<member.*type=\"way\".*ref=' ${osmfile} > ${WAYSFILE}

#	declare -A ways
	local ways=()
	[ -d "${TMPDIR}/gpx" ] || mkdir -p "${TMPDIR}/gpx" || exit 1
	while read -r line; do
		#echo "$line"
		local refway=$(echo -n $line | grep -oP '<member(.*) type=\"way\"(.*) ref="\K[^"]*')
		local role=$(echo -n $line | grep -oP '<member(.*) type=\"way\"(.*) role="\K[^"]*')
		local gpxFile="${TMPDIR}/gpx/${refway}-${role}.gpx"
		checkFileTime ${gpxFile} || generateWay ${refway} ${role} > ${gpxFile}
#		echo "GPX: ${gpxFile}" >&2
		ways+=(${gpxFile})
	done < ${WAYSFILE}
	rm -vf ${WAYSFILE} >&2
	echo "obejctid=${objectid} relid=${relid}" >&2
	local rels=()
	if [ "${objectid}" == "${relid}" ]; then
		echo "Relations of ${relid}" >&2 
		#test -d "gpx/${objectid}" || mkdir -p "gpx/${objectid}"
		while IFS= read -r line; do
			echo -e "\nExecute: $0 rel${line}" >&2
			local filename="${line}.gpx"
			generateRelation ${line}
#			mv -v ${filename} "${TMPDIR}/gpx/${objectid}.gpx"
			rels+=(${filename})
		done < <(grep -oP '<member(.*) type=\"relation\"(.*) ref="\K[^"]*' ${osmfile})
	fi;

	if [ ${#ways[@]} -eq 0 ] && [ ${#rels[@]} -eq 0 ]; then
		echo "Empty ways and relations..." >&2
		return 1;
	fi;
	
	local RELFILE=$(mktemp) || exit 1

#	for wayfile in "${ways[@]}"; do
#		echo "way=$wayfile"
#	done;
#	for wayfile in "${rels[@]}"; do
#		echo "rels=$wayfile"
#	done;

	for wayfile in "${ways[@]}"; do
		ts=$(sed -n "/<metadata/,/<\/metadata>/p" "${wayfile}" | grep "<time>" | sed -e "s/<time>\(.*\)<\/time>/\1/" | tr -d '\t')
		echo "Extract <time> from ${wayfile} is ${ts}" >&2
		minlat=$(sed -n "/<metadata/,/<\/metadata>/p" "${wayfile}" | grep -oP '<bounds(.*) minlat="\K[^"]*')
		maxlat=$(sed -n "/<metadata/,/<\/metadata>/p" "${wayfile}" | grep -oP '<bounds(.*) maxlat="\K[^"]*')
		minlon=$(sed -n "/<metadata/,/<\/metadata>/p" "${wayfile}" | grep -oP '<bounds(.*) minlon="\K[^"]*')
		maxlon=$(sed -n "/<metadata/,/<\/metadata>/p" "${wayfile}" | grep -oP '<bounds(.*) maxlon="\K[^"]*')
		echo "${wayfile##*\/} ${minlat},${minlon} ${ts}" >> ${RELFILE} 
		echo "${wayfile##*\/} ${maxlat},${maxlon} ${ts}" >> ${RELFILE} 
	done
	for wayfile in "${rels[@]}"; do
		ts=$(sed -n "/<metadata/,/<\/metadata>/p" "${wayfile}" | grep "<time>" | sed -e "s/<time>\(.*\)<\/time>/\1/" | tr -d '\t')
		echo "Extract <time> from ${wayfile} is ${ts}" >&2
		minlat=$(sed -n "/<metadata/,/<\/metadata>/p" "${wayfile}" | grep -oP '<bounds(.*) minlat="\K[^"]*')
		maxlat=$(sed -n "/<metadata/,/<\/metadata>/p" "${wayfile}" | grep -oP '<bounds(.*) maxlat="\K[^"]*')
		minlon=$(sed -n "/<metadata/,/<\/metadata>/p" "${wayfile}" | grep -oP '<bounds(.*) minlon="\K[^"]*')
		maxlon=$(sed -n "/<metadata/,/<\/metadata>/p" "${wayfile}" | grep -oP '<bounds(.*) maxlon="\K[^"]*')
		echo "${wayfile##*\/} ${minlat},${minlon} ${ts}" >> ${RELFILE} 
		echo "${wayfile##*\/} ${maxlat},${maxlon} ${ts}" >> ${RELFILE} 
	done

	#echo "Max date "` TZ='Z' date --date="@$ts" +'%FT%X%ZZ'`
	read -r -d '' latmin latmax lonmin lonmax lastts <<< $(getBoundary ${RELFILE} )
	rm ${RELFILE} >&2
	lastts=$(echo -e "${lastts}\n${relts}" | sort -r | head -n 1)
	echo "Last update "`date -d "${lastts}" +"%F %T %Z"` >&2

	local year=$(date +%Y)
	local gpx_metadata="\t<metadata>\n\t</metadata>"
	[ "${name}" != "" ] && gpx_metadata=${gpx_metadata/"\t</metadata>"/"\t\t<name>${name}</name>\n\t</metadata>"}
	[ "${desc}${note}" != "" ] && gpx_metadata=${gpx_metadata/"\t</metadata>"/"\t\t<desc>${desc}${note}</desc>\n\t</metadata>"}
	[ "${author}" != "" ] && gpx_metadata=${gpx_metadata/"\t</metadata>"/"\t\t<author>\n\t\t\t<name>${author}</name>\n\t\t</author>\n\t</metadata>"}
	gpx_metadata=${gpx_metadata/"\t</metadata>"/"\t\t<copyright author=\"© OpenStreetMap contributors\">\n\t\t\t<year>${year}</year>\n\t\t\t<license>https://opendatacommons.org/licenses/odbl/</license>\n\t\t</copyright>\n\t</metadata>"}
	[ "${website}" != "" ] && gpx_metadata=${gpx_metadata/"\t</metadata>"/"\t\t<link href=\"${website}\"/>\n\t</metadata>"}
	[ "${lastts}" != "" ] && gpx_metadata=${gpx_metadata/"\t</metadata>"/"\t\t<time>${lastts}</time>\n\t</metadata>"}
	[ "${name}" != "" ] && echo "Name: ${name}" >&2
	[ "${operator}" != "" ] && echo "Operator: ${operator}" >&2
	[ "${network}" != "" ] && echo "Network: ${network}" >&2
	colour=$(checkGarminColour ${colour})
	if [ $? -eq 0 ]; then
		echo "Color: ${colour}" >&2
		extension="<extensions>\n\t\t\t<gpxx:TrackExtension xmlns:gpxx=\"http://www.garmin.com/xmlschemas/GpxExtensions/v3\">\n\t\t\t\t<gpxx:DisplayColor>${colour}</gpxx:DisplayColor>\n\t\t\t</gpxx:TrackExtension>\n\t\t</extensions>"
#		gpx_metadata=${gpx_metadata/"\t</metadata>"/"\t\t${extension}\n\t</metadata>"}
	fi;

	gpx_metadata=${gpx_metadata/"\t</metadata>"/"\t\t<bounds minlat=\"${latmin}\" maxlat=\"${latmax}\" minlon=\"${lonmin}\" maxlon=\"${lonmax}\"/>\n\t</metadata>"}

	local gpxrel=$(mktemp)
	echo "Create temporaly file $gpxrel" >&2
	echo -e "${gpx_start}" > ${gpxrel}
	echo -e "${gpx_metadata}" >> ${gpxrel}

	
	if [ ${#ways[@]} -ne 0 ]; then

		echo -e "\t<trk>" >> "${relid}.gpx"  >> ${gpxrel}
		[ "${name}" != "" ] && echo -e "\t\t<name>${name}</name>" >> ${gpxrel}
		[ "${note}" != "" ] && echo -e "\t\t<cmt>${note}</cmt>" >> ${gpxrel}
		[ "${desc}" != "" ] && echo -e "\t\t<desc>${desc}</desc>" >> ${gpxrel}
		echo -e "\t\t<src>OpenStreetMap</src>" >> ${gpxrel}
		if [ "${website}" != "" ]; then
			echo -e "\t\t<link href=\"${website}\"><text>${name}</text></link>" >> ${gpxrel}
		else
			echo -e "\t\t<link href=\"https://www.openstreetmap.org/relation/${relid}\"><text>${relid}</text></link>" >> ${gpxrel}
		fi;
		echo -e "\t\t<number>${relid}</number>" >> ${gpxrel}
		echo -e "\t\t<type>path</type>" >> ${gpxrel}
		[ "${extension}" != "" ] && echo -e "\t\t${extension}" >> ${gpxrel}
		if [ "${parted}" == "true" ]; then
			for wayfile in "${ways[@]}"; do
				echo "Extract <trkseg> from ${wayfile}" >&2
				# Include trkseg
				sed -n "/<trkseg>/,/<\/trkseg>/p" "${wayfile}" >> ${gpxrel}
			done
		else
			echo -e "\t\t<trkseg>" >> ${gpxrel}
	# https://stackoverflow.com/questions/38972736/how-to-print-lines-between-two-patterns-inclusive-or-exclusive-in-sed-awk-or
			for wayfile in "${ways[@]}"; do
				#echo "A3 ${wayfile}" >&2
				awk "${patternTrkSeg}" "${wayfile}" | head -n -1 >> ${gpxrel}
			done
			awk "${patternTrkSeg}" "${wayfile}" | tail -n 1 >> ${gpxrel}
			echo -e "\t\t</trkseg>" >> ${gpxrel}
		fi;
		echo -e "\t</trk>" >> ${gpxrel}
	fi;

	if [ ${#rels[@]} -ne 0 ]; then
	#	awk 'flag{ if (/PAT2/){printf "%s", buf; flag=0; buf=""} else buf = buf $0 ORS}; /PAT1/{flag=1}' file
		for wayfile in "${rels[@]}"; do
			echo "Extract <trk> from ${wayfile}" >&2
			echo -e "\t<trk>" >> ${gpxrel}
			awk "${patternTrk}" "${wayfile}" >> ${gpxrel}
			echo -e "\n\t</trk>" >> ${gpxrel}
		done
	fi;
	echo "</gpx>" >> ${gpxrel}
	
	# Check distance
	if [ "${checkDistance}" == "true" ]; then
		local masterdist=0
		local c=0
		local endcoo;
		local coo;
		for wayfile in "${ways[@]}"; do
		while IFS= read -r line; do
	#		echo "line '${line}'"
			if [[ $line == *"<trkpt"* ]]; then
				lat=$(echo ${line} | grep -oP '<trkpt(.*) lat="\K[^"]*' | tr -d '\n')
				lon=$(echo ${line} | grep -oP '<trkpt(.*) lon="\K[^"]*' | tr -d '\n')
				coo="${lat},${lon}"
				[ "${lastcoo}" != "" ] && subdist=$(addFloat ${subdist:-0} $(distance ${coo} ${lastcoo}))
				lastcoo=${coo}
				if [ "$endcoo" != "" ]; then
					[ "${coo}" != "${endcoo}" ] && echo -e "Incorrect start coordinate ${coo} of connection on '${wayfile##*\/}' (part $c)!" >&2
					unset endcoo
				fi;
			elif [[ $line == *"<trkseg>"* ]]; then
				subdist=0
				c=$(($c + 1))
	#			echo "START subdist=${subdist}" >&2
			elif [[ $line == *"</trkseg>"* ]]; then
				masterdist=$(addFloat ${masterdist:-0} ${subdist:-0})
				endcoo=$lastcoo
				echo "$c / ${#ways[@]} ${wayfile##*\/} ${masterdist} km"
			fi;
		done < <(sed -n "/<trkseg>/,/<\/trkseg>/p" "${wayfile}")
		done
		echo "GPX distance $masterdist km (${distance})"
		[ ${distance:-0} == "0" ] || echo "Distance in OSM relation($relid) is $distance km (diff "$(bc -l <<<"scale=1;100*${masterdist:-0}/${distance}")"%)"
	fi;
	cat ${gpxrel}
	rm ${gpxrel}
}

if [ "${type}" == "rel" ]; then
	echo "Generate relation id=${objectid}" >&2
	generateRelation ${objectid}
else
	echo "Generate way id=${objectid}" >&2
	if [ "${gpxfile}" != "" ]; then
		generateWay ${objectid} ${reverse} > ${gpxfile}
		echo "Created GPX file ${gpxfile}"
		if [ "${validate}" == "true" ]; then
				xmllint --noout --schema http://www.topografix.com/GPX/1/1/gpx.xsd ${gpxfile} || echo "Bad validation!" >&2
		fi;
		#gpxfile="${wayid}.gpx"
#		echo "GPX to file> '${gpxfile}'" >&2
#		exec 3<&-
	#	Open STDOUT as $LOG_FILE file for read and write.
#		exec 3<>${gpxfile}
#		echo "Create GPX file ${gpxfile}" >&2
	else
		generateWay ${objectid} ${reverse}
	fi;
	
	
	
fi;






